config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # devise_for :users
  post "/booking/destroy", to: "bookings#destroy", as: "booking_destroy"
  delete "/sessions/destroy", to: "devise/sessions#destroy"
  root to: 'pages#home'
  resources :courses, only: [ :index, :show ] do
    resources :bookings, only: [ :new, :create ]
    resources :chatrooms, only: [ :show, :new, :create ] do
      resources :messages, only: :create
    end
  end
  resources :bookings, only: [ :index, :show, :edit, :update, :destroy ]
  resources :pages, only: [ :index, :edit, :update ]
  get 'profile', to: 'pages#profile'
  get 'admin', to: 'pages#admin'
  resources :chatrooms, only: [ :show, :new, :create ] do
    resources :messages, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
  belongs_to :course
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :institution
  has_many :bookings
  has_one :chatroom

  validates :title, presence: true
  validates :professor, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  # validates :subject, inclusion: { in: %w(Art and Design Business & Economics Computer Science Education Engineering Geography History Languages Law Medicine Philosophy Politics and International Relations Sciences Sport Studies), message: "Please choose a subject"}
  validates :price, presence: true, numericality: { only_integer: true }
  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date

  include PgSearch::Model
  pg_search_scope :search_by_title_and_description,
      against: %i[title description ],
      associated_against: {
      institution: [ :name ]
    },
      using: {
        tsearch: {
          prefix: true
        }
      }
  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end
end

app/models/institution.rb
class Institution < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :courses
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true, length: { minimum: 10 }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  skip_before_action :verify_authenticity_token

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [ :show, :destroy ]
  before_action :set_user
  # Need to make sure this displays bookings for the current user only
  def index
    @bookings = Booking.where(user: current_user)
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new # function to create a new booking
    @course = Course.find(params[:course_id])
    @booking.user = current_user
    @booking.course = @course
    @booking.save
    if @booking.save!
      redirect_to bookings_path
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    @bookings = current_user.bookings
    render "pages/profile"
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:course_id, :user_id)
  end

  def set_user
    if user_signed_in?
      @user = current_user
    end
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :set_user

  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
    @course = Course.find(@chatroom.course_id)
  end

  def new
    @chatroom = Chatroom.new
  end

  def create
    @chatroom = Chatroom.new
    @course = Course.find(params[:course_id])
    @chatroom.user = current_user
    @chatroom.course = @course
    @chatroom.save
    if @chatroom.save!
      redirect_to chatrooms_path
    else
      render :new
    end
  end

  private

  def set_user
    if user_signed_in?
      @user = current_user
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # before_action :set_user, except: [:index, :show]

  def index
    # Add the folli=owing lines of code when we implement a search bar
    if params[:query].present?
      courses_by_query = Course.search_by_title_and_description(params[:query])
      @courses = courses_by_query
      if params[:institution].present? && params[:institution][:id].present?
        @courses =  courses_by_query(institution: params[:institution][:id])
      end
    elsif params[:institution].present? && params[:institution][:id].present?
      @courses =  Course.all.where(institution: params[:institution][:id])
    else
      @courses = Course.all
    end
    @user = current_user

    # @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
    @booking = Booking.new
    @institution = @course.institution
    @markers = [{
    lat: @institution.latitude,
    lon: @institution.longitude
    }]
    # @markers2 = @markers1.to_json
    # @markers = @institution.geocode.map do |i|
    #   {
    #     lat: i,
    #     lon: i
    #   }
    # end
  end

  private

  def course_params
    params.require(:game).permit(:professor, :title, :description, :subject, :price, :start_date, :end_date, :rating)
  end

  # def set_user
  #   @user = current_user
  # end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    if @message.save
      ChatroomChannel.broadcast_to(
        @chatroom,
        render_to_string(partial: "message", locals: { message: @message })
      )
      redirect_to chatroom_path(@chatroom)
    else
      render "chatrooms/show"
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:home]
  def home
    # random coment
    @courses = Course.order("rating DESC")
  end
  def admin
  end
  
  def profile
    @user = current_user
    @bookings = current_user.bookings
  end

  def edit
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="confirmation-banner" style="background-image: linear-gradient(-225deg, #231B1B 0%, rgba(0,36,61,0.6) 50%), url('https://www.hoteldonandres.com/wp-content/uploads/2016/10/blackboard.jpg')">
  <div class="banner-content">
    <i class="fa-solid fa-check fa-8x"></i>
    <h1>Thanks for booking with <span class=red>Re</span>Chair</h1>
    <p> You're all set! You'll receive an email from your institution confirming your Chair and further details on your chosen course. </p>
    <p>To view and manage your bookings, head over to your <%= link_to "profile page", profile_path %></p>
    <%= form_with url: "courses", method: :get do |form| %>
    <%= form.submit "Discover more", class: "btn btn-primary btn-lg" %>
  <% end %>
</div>

app/views/chatrooms/show.html.erb
<div style="width:50%; margin:auto">
  <h2>Join the #<%= @chatroom.name %></h2>
  <h5>for <%= @course.title %> </h5>
  <br>
  <div style="border-radius:40px; background-color:#282D32; box-shadow: 5px 5px 12px -1px rgba(0,0,0,0.25);">
    <div id="messages" data-chatroom-id="<%= @chatroom.id %>" style="height:70vh; overflow:scroll;  overflow-x: hidden; padding:40px;">
      <% @chatroom.messages.each do |message| %>
        <%= render 'messages/message', message: message %>
      <% end %>
    </div>

    <%# Simple form for messages %>
    <div class="message-form-wrapper">
      <%= simple_form_for [ @chatroom, @message ], html: { autocomplete: 'off' }, remote: true do |f| %>
      <%= f.input :content, label: false, placeholder: "Message ##{@chatroom.name} for #{@course.title}" %>
      <% end %>
    </div>
  </div>
  <br>
  <br>
</div>

app/views/courses/index.html.erb
<div id="wrapper" style="width:80%; margin:auto">
  <div class="index-search">
    <div class= "search-item">
      <%= form_tag courses_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find a course"
        %>
      </div>
      <div class= "search-item">
        <%= collection_select :institution, :id, Institution.all, :id, :name, { :include_blank => true }, { :selected => params[:institution] ? params[:institution][:id] : nil, :class => "custom-select" } %>
      </div>
      <div class= "search-item">
        <%= submit_tag "Search", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>

  <div class="container-fluid">
    <div class="cards">
      <% @courses.each do |course| %>
        <div>
          <div class="card-product">
            <div class="row">
              <div class="col">
                <%= link_to course_path(course) do %>
                <img src="<%=course.image_url%>">
                <% end %>
              </div>
            </div>
            <%# Course title, Institution name, and Description %>
            <div class="row">
              <div class="col">
                <div class="text-center">
                  <h5><%= link_to course.title, course_path(course) %>, </h5>
                  <h6>at <%= course.institution.name %></h6> <%# add link to institution profile page %>
                </div>
                <div class="text-left">
                  <p><%= course.description.first(75) %>...</p>
                </div>
              </div>
            </div>
            <%# Professor name and Price %>
            <div class="d-flex justify-content-between card-bottom">
              <p>Prof. <%= course.professor %></p>
              <p><i style="color:#8EB1C7" class="fa-solid fa-star"></i> <%= course.rating.round(1) %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/courses/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @institution.image_url%>);">
  <div class="container-show">
  <div id="wrapper" style="width:80%; margin:auto">
    <h1 style="justify-content:center"><%= @course.institution.name %></h1>
  </div>
  </div>
</div>

<div id="wrapper-show" style="width:80%; margin:auto;">
  <div class="course-page-title" style="justify-content: space-between">
    <h3> <%= @course.title %> </h3>
    <h3 style=" text-shadow: 2px 2px 1px rgba(0, 0, 0, 0.4);"> <i class="fa-solid fa-star" style="color:#8EB1C7; text-shadow: 2px 2px 1px rgba(0, 0, 0, 0.4);"></i> <%= @course.rating.round(1) %> </h3>
  </div>

  <hr>

<div id="show-content" style="display:flex; justify-content:space-between">
  <div class="description-section" style="width:50%">
    <p> <b>Description:</b> </p>
    <p> <%= @course.description %> </p>

    <br>
    <br>

  </div>
    <div class="course-info-and-map" style="width:50%">
        <%# Course info card %>
      <div class="card-product-show">
      <img src="<%=@course.image_url%>" />
        <div class="card-product-infos-show" id="card-product-infos-show-p">
          <p> <b>Subject:</b> <%= @course.subject %> </p>
          <p> <b>Start date:</b> <%= @course.start_date %> </p>
          <p> <b>End date:</b> <%= @course.end_date %> </p>
          <p> <b>Price:</b> £<%= @course.price %> </p>
      <br>
          <% if current_user.bookings.where(course_id: @course.id) == [] %>
            <%= simple_form_for [@course, Booking.new] do |f| %>
              <%= f.submit "Reserve Chair", class: "btn btn-primary", id: "reservation-btn", data: {course_id: @course.id, user_id: current_user.id} %>
            <% end %>
            <%else%>
            <%= link_to "Join our roundtable",  chatroom_path , class:"btn btn-primary"%>
          <% end %>
        </div>
      </div>
    <div class="map-section">
    <br>
      <h5>Find Us </h5>
      <div class="map-container">
        <div id="map"
        style="width: 100%; height: 200px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
     <br>
     <h6>Address: <%= @institution.address%></h6>
  </div>
</div>
    </div>

</div>



<br>
<br>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RECHAIR</title>
    <script src="https://kit.fontawesome.com/427c175c33.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('rechair_logo.png') %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <script src="https://kit.fontawesome.com/4ee373f793.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_pack_tag 'map' %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message-container" id="message-<%= message.id %>">
  <p style="margin-bottom: 4px"><%= message.user.first_name %> <%= message.user.last_name %> wrote:</p>
  <h5 style="background-color: #8EB1C7; border-radius: 15px; padding-left: 20px; padding-right: 20px; padding-top:2px; padding-bottom:2px; width: fit-content; margin-left:10px"><%= message.content %></h5>
  <i class="author">
  <p class="message-date" style="margin-left:10px"><%= message.created_at.strftime("%a %b %e at %l:%M%p") %></p>
  </i>
  <br>
</div>

app/views/pages/admin.html.erb
<h1>Welcome Joe</h1>

app/views/pages/edit.html.erb
<h1>Some day you'll be able to edit your profile here.</h1>
<p>Sadly, that day is not today</p>

app/views/pages/home.html.erb
<%# Banner %>
<div class="banner" >
  <div class ="container">
    <div class="banner-content">
      <h1><span class=red>Re</span>Chair</h1>
      <p>Every chair is an opportunity</p>
      <%= link_to "Browse Chairs", courses_path, class:"btn btn-primary"%>
    </div>
  </div>
</div>
<br>
<br>

<div id="wrapper" style="width:80%; margin:auto">
<%# About Us Section %>
  <div class="card-mission">
    <h3 style="font-weight: bold; text-align: center; padding:20px;"> Our Mission </h3>
    <div class="text-center">
      <h5 id="about-us-text"style="width:80%; margin:auto">We believe vacant seats on courses is a missed opportunity for someone out there. That’s why we’ve partnered with universities to promote their vacant seats at an affordable rate. Those who have a passion for education and learning will be able to do so by booking their ideal course with Rechair.</h5>
    </div>
  </div>
  <br>
  <br>

<%# Carousel %>
<h3 style="font-weight: bold; text-align: center; padding:20px;"> Our Partners </h3>
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag "Carousel1.jpg", alt: "orange", class: "d-block w-100" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "Carousel2.jpg", alt: "orange", class: "d-block w-100" %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<br>
<%# TopRatedCourses %>
<h3 style="font-weight: bold; text-align: center; padding:20px;"> Top Courses </h3>

  <div class="cards">
    <% @courses.first(3).each do |course| %>
      <div>
        <div class="card-product">
          <div class="row">
            <div class="col">
              <%= link_to course_path(course) do %>
               <img src="<%=course.image_url%>">
              <% end %>
            </div>
          </div>
          <%# Course title, Institution name, and Description %>
          <div class="row">
            <div class="col">
              <div class="text-center">
                <h5><%= link_to course.title, course_path(course) %>, </h5>
                <h6>at <%= course.institution.name %></h6> <%# add link to institution profile page %>
              </div>
              <div class="text-left">
                <p><%= course.description.first(90) %>...</p>
              </div>
            </div>
          </div>
          <%# Professor name and Price %>
          <div class="d-flex justify-content-between card-bottom">
            <p>Prof. <%= course.professor %></p>
            <p><i style="color:#8EB1C7" class="fa-solid fa-star"></i> <%= course.rating.round(1) %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <br>
  <br>
  <br>
</div>

app/views/pages/profile.html.erb
<div id="wrapper" style="width:80%; margin:auto">
<div class="container-fluid">

  <h3 id="profile-h1">Hi, <%= @user.first_name %></h3>
  <br><br>

  <div style="background:#F4F4F4; border-radius:25px; height:110%">
  <div class="flex-container">
    <div >
      <img style="border-radius: 50%; length:200px; height:200px; padding-left:20px" src="<%= @user.profile_pic_url %>">
    </div>

    <div>

      <p style="color: black; font-size: 30px;">Name: <%= @user.first_name %> <%= @user.last_name %></p>
      <p style="color: black; font-size: 20px">Email: <%= @user.email %></p>
      <div>
        <%= link_to "Edit profile", edit_page_path(:id) %>
      </div>
    </div>
  </div>
</div>
</div>
  <hr>

</div>
<div>

  <div class="container-fluid">
    <h3>My Bookings</h3>
    <h5 style="centered">Let's see what courses you have coming up...</h5>


  <div class="container-fluid">
    <div class="cards">
      <% @bookings.each do |booking| %>
        <div>
          <div class="card-product d-flex flex-column justify-content-between">
          <div>
            <div class="row">
              <div class="col">
              <%= link_to course_path(booking.course) do %>
                <img src="<%= booking.course.image_url %>">
                <% end %>
              </div>
            </div>
            <%# Course title, Institution name, and Description %>
            <div class="row">
              <div class="col">
                <div class="text-center">
                  <h5> <%= link_to booking.course.title, course_path(booking.course) %> </h5>
                  <h6>at <%= link_to booking.course.institution.name, course_path(booking.course) %></h6> <%# add link to institution profile page %>
                </div>
                <div class="d-flex justify-content-around">
                  <p> Start: <%= booking.course.start_date  %> </p>
                  <p> End: <%= booking.course.end_date  %> </p>
                </div>
              </div>
            </div>
          </div>
            <i class="fa-solid fa-xmark delete-btn pb-3" data-booking-id="<%= booking.id %>"></i>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

  <div class="container-fluid">
    <div class="d-flex justify-content-center">
      <div id="profile-discover-bttn">
        <%# <%= link_to "Find a course to study", courses_path %>
        <a class="btn btn-primary" href="/courses">Discover More</a>
      </div>
    </div>
  </div>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
    <div class="footer-dark">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Services</h3>
                        <ul>
                            <li><a href="#">Contact Support</a></li>
                            <li><a href="#">Feedback</a></li>
                            <li><a href="#">Report a problem</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>About</h3>
                        <ul>
                            <li><a href="#">Company</a></li>
                            <li><a href="#">Team</a></li>
                            <li><a href="#">Careers</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6 item text">
                        <h3>Rechair</h3>
                        <p>We strive to provide formal education for everyone. Our goal is to fill up all the free spaces at universities and make maximum use of the great minds that teach. Education is a cornerstone for becoming a better individual.</p>
                    </div>
                    <div class="col item social"><a href="#"><i class="fa-brands fa-facebook-square"></i></a><a href="#"><i class="fa-brands fa-twitter-square"></i></a><a href="#"><i class="fa-brands fa-snapchat-square"></i></a><a href="#"><i class="fa-brands fa-instagram-square"></i></a></div>
                </div>
                <p class="copyright">Rechair © 2022</p>
            </div>
        </footer>
    </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "rechair_logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

        <% if user_signed_in? %>

          <li class="nav-item dropdown">
            <%= image_tag "Header-avatar-01-white.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", 'data-toggle':"dropdown", 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "View Profile", profile_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>

          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>